/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-29 07:00:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" xmlns:th=\"http://www.thymeleaf.org\" xmlns:sec=\"http://www.w3.org/1999/xhtml\">>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../static/css/style2.css\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body th:fragment = \"header\">\r\n");
      out.write("<div class=\"main\" style=\"height: 250px;\r\n");
      out.write("         width: 100%;\">\r\n");
      out.write("    <nav class=\"notion_header\">\r\n");
      out.write("        <div class=\"usermenu\" style=\"position: absolute; width: 500px; right: 13%; margin: 0 -150px 0 0; font-size: 15px;\">\r\n");
      out.write("            <nav id=\"sub-menu\">\r\n");
      out.write("                <ul class=\"dep1\">\r\n");
      out.write("                    <li class=\"usermenuli\" th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.user == null && session.admin == null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><a class=\"subusermenuli\" th:href=\"@{/user/join}\">회원가입</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.user == null && session.admin == null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"usermenuli\"><a class=\"subusermenuli\" th:href=\"@{/login}\">로그인</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"usermenuli\" th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.user != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><a class=\"subusermenuli\" th:href=\"@{/userlogout}\">로그아웃</a></li>\r\n");
      out.write("                    <li class=\"usermenuli\" th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.admin != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><a class=\"subusermenuli\"  th:href=\"@{/adminlogout}\">로그아웃</a></li>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"usermenuli\" th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.user != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ><span class=\"subusermenuli\" th:text = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span></li>\r\n");
      out.write("                    <li class=\"usermenuli\" th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.admin != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ><a class=\"subusermenuli\" th:href=\"@{/adminUser}\"><span th:text = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.admin.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></span></a></li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"usermenuli\" th:if = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.user != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><a class=\"subusermenuli\" href=\"#\">마이페이지</a>\r\n");
      out.write("                        <ul class=\"sub-menu2\">\r\n");
      out.write("                            <li class=\"usermenuli2\"><a class=\"subusermenu\" th:href=\"@{/orderlist}\" >주문목록</a></li>\r\n");
      out.write("                            <li class=\"usermenuli2\"><a class=\"subusermenu\"  th:href=\"@{/membercheck}\">개인정보</a></li>\r\n");
      out.write("                            <li class=\"usermenuli2\"><a class=\"subusermenu\" th:href=\"@{/cart}\">장바구니</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"usermenuli\"><a class=\"subusermenuli\" href=\"#\">고객센터</a>\r\n");
      out.write("                        <ul class=\"sub-menu2\">\r\n");
      out.write("                            <li class=\"usermenuli2\"><a class=\"subusermenu\" th:href=\"@{/notionmain}\">공지사항</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a th:href=\"@{/}\">\r\n");
      out.write("            <img src=\"../static/img/Logo.png\" alt=\"모두의레시피\"\r\n");
      out.write("                 style=\"display: block; margin: 0px auto;\"\r\n");
      out.write("            ></a>\r\n");
      out.write("        <nav class=\"navigation\" style=\"position: absolute; width: 900px; height:56px; left: 50%; margin: 0 0 0 -450px; left:450px;\">\r\n");
      out.write("            <div id=\"nav\">\r\n");
      out.write("                <ul class=\"menulist\" style=\"position: relative; top: 15px; height:45px;\">\r\n");
      out.write("                    <li class=\"menu\"><a class=\"menu-a\" th:href=\"@{/new}\">New</a>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"menu\"><a class=\"menu-a\" th:href=\"@{/best}\">Best</a>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"menu\"><a class=\"menu-a\" href=\"#\"\r\n");
      out.write("                                        style=\"position: relative; right: 10px;\"\r\n");
      out.write("                    >Creator</a>\r\n");
      out.write("                        <ul class=navsub id=\"creatorsub\" style=\"width: 90px;\">\r\n");
      out.write("                            <li><a class=\"menusubsub\" th:href=\"@{/recipelist/백종원}\">백종원</a></li>\r\n");
      out.write("                            <li><a class=\"menusubsub\" th:href=\"@{/recipelist/이연복}\">이연복</a></li>\r\n");
      out.write("                            <li><a class=\"menusubsub\" th:href=\"@{/recipelist/레이먼킴}\">레이먼킴</a></li>\r\n");
      out.write("                            <li><a class=\"menusubsub\" th:href=\"@{/recipelist/이혜정}\">이혜정</a></li>\r\n");
      out.write("                        </ul></li>\r\n");
      out.write("                    <li class=\"menu\"><a class=\"menu-a\" href=\"#\">MENU</a>\r\n");
      out.write("                        <ul class=\"navsub\" id=\"menusub\">\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/koreanfood.png\"><a class=\"menusubsub\" th:href=\"@{/menu/한식}\">한식</a></li>\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/sushi.png\"><a class=\"menusubsub\" th:href=\"@{/menu/일식}\">일식</a></li>\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/steak.png\"><a class=\"menusubsub\" th:href=\"@{/menu/양식}\">양식</a></li>\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/jjajang.png\"><a class=\"menusubsub\" th:href=\"@{/menu/중식}\">중식</a></li>\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/dduk.png\"><a class=\"menusubsub\" th:href=\"@{/menu/분식}\">분식</a></li>\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/chicken.png\"><a class=\"menusubsub\" th:href=\"@{/menu/치킨}\">치킨</a></li>\r\n");
      out.write("                            <li class=\"menusub\"><img class=\"menusubsubimg\" src=\"../static/img/pizza.png\"><a class=\"menusubsub\" th:href=\"@{/menu/피자}\">피자</a></li>\r\n");
      out.write("                        </ul></li>\r\n");
      out.write("                    <li class=\"menu\"><a class=\"menu-a\" th:href=\"@{/meterialMain}\">Material</a>\r\n");
      out.write("                        <ul class=\"navsub\" id=\"materialsub\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/meat.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/정육}\">정육</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/fish.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/수산}\">수산|해산</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/noodle.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/면}\">면|견과</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/fruits.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/과일}\">과일</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/vegetable.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/채소}\">채소</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/bread.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/베이커리}\">베이커리</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/sauce.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/양념}\">양념|오일</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img class=\"menusubsubimg\" src=\"../static/img/milk.png\">\r\n");
      out.write("                                <a class=\"menusubsub\" th:href=\"@{/meterialMain/계란}\">계란|유제품</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"searchboxdiv\"   style=\"position:relative; width:250px; left:560px; bottom:35px;\">\r\n");
      out.write("                    <input class=\"searchbox\" type=\"text\" placeholder=\"&nbsp오늘은 어떤 요리를 만들까요?\" name=\"keyword\">\r\n");
      out.write("                    <button class=\"searchbtn\"  style=\"font-family: 'NanumSquareRound'; width: 32px; height: 32px; border: none; cursor: pointer;\">\r\n");
      out.write("                        <img src=\"../static/img/button_search.png\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
