/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-29 04:21:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js\" integrity=\"sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<link href=\"carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"d-none\">\r\n");
      out.write("      <symbol id=\"check2\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"circle-half\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"moon-stars-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z\"/>\r\n");
      out.write("        <path d=\"M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("      <symbol id=\"sun-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("        <path d=\"M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z\"/>\r\n");
      out.write("      </symbol>\r\n");
      out.write("    </svg>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle\">\r\n");
      out.write("      <button class=\"btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("              id=\"bd-theme\"\r\n");
      out.write("              type=\"button\"\r\n");
      out.write("              aria-expanded=\"false\"\r\n");
      out.write("              data-bs-toggle=\"dropdown\"\r\n");
      out.write("              aria-label=\"Toggle theme (auto)\">\r\n");
      out.write("        <svg class=\"bi my-1 theme-icon-active\" width=\"1em\" height=\"1em\"><use href=\"#circle-half\"></use></svg>\r\n");
      out.write("        <span class=\"visually-hidden\" id=\"bd-theme-text\">Toggle theme</span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <ul class=\"dropdown-menu dropdown-menu-end shadow\" aria-labelledby=\"bd-theme-text\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <button type=\"button\" class=\"dropdown-item d-flex align-items-center\" data-bs-theme-value=\"light\" aria-pressed=\"false\">\r\n");
      out.write("            <svg class=\"bi me-2 opacity-50 theme-icon\" width=\"1em\" height=\"1em\"><use href=\"#sun-fill\"></use></svg>\r\n");
      out.write("            Light\r\n");
      out.write("            <svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\"><use href=\"#check2\"></use></svg>\r\n");
      out.write("          </button>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <button type=\"button\" class=\"dropdown-item d-flex align-items-center\" data-bs-theme-value=\"dark\" aria-pressed=\"false\">\r\n");
      out.write("            <svg class=\"bi me-2 opacity-50 theme-icon\" width=\"1em\" height=\"1em\"><use href=\"#moon-stars-fill\"></use></svg>\r\n");
      out.write("            Dark\r\n");
      out.write("            <svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\"><use href=\"#check2\"></use></svg>\r\n");
      out.write("          </button>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <button type=\"button\" class=\"dropdown-item d-flex align-items-center active\" data-bs-theme-value=\"auto\" aria-pressed=\"true\">\r\n");
      out.write("            <svg class=\"bi me-2 opacity-50 theme-icon\" width=\"1em\" height=\"1em\"><use href=\"#circle-half\"></use></svg>\r\n");
      out.write("            Auto\r\n");
      out.write("            <svg class=\"bi ms-auto d-none\" width=\"1em\" height=\"1em\"><use href=\"#check2\"></use></svg>\r\n");
      out.write("          </button>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"py-2 bg-body-tertiary border-bottom\">\r\n");
      out.write("    <div class=\"container d-flex flex-wrap\">\r\n");
      out.write("      <ul class=\"nav me-auto\">\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2 active\" aria-current=\"page\">Home</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2\">Features</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2\">Pricing</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2\">FAQs</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2\">About</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav\">\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2\">Login</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a href=\"#\" class=\"nav-link link-body-emphasis px-2\">Sign up</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <header class=\"py-3 mb-4 border-bottom\">\r\n");
      out.write("    <div class=\"container d-flex flex-wrap justify-content-center\">\r\n");
      out.write("      <a href=\"/\" class=\"d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none\">\r\n");
      out.write("        <svg class=\"bi me-2\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg>\r\n");
      out.write("        <span class=\"fs-4\">Double header</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <form class=\"col-12 col-lg-auto mb-3 mb-lg-0\" role=\"search\">\r\n");
      out.write("        <input type=\"search\" class=\"form-control\" placeholder=\"Search...\" aria-label=\"Search\">\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide mb-6\" data-bs-ride=\"carousel\">\r\n");
      out.write("    <div class=\"carousel-indicators\">\r\n");
      out.write("      <button type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("      <button type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("      <button type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item active\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"carousel-caption text-start\">\r\n");
      out.write("            <h1>Example headline.</h1>\r\n");
      out.write("            <p class=\"opacity-75\">Some representative placeholder content for the first slide of the carousel.</p>\r\n");
      out.write("            <p><a class=\"btn btn-lg btn-primary\" href=\"#\">Sign up today</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"carousel-caption\">\r\n");
      out.write("            <h1>Another example headline.</h1>\r\n");
      out.write("            <p>Some representative placeholder content for the second slide of the carousel.</p>\r\n");
      out.write("            <p><a class=\"btn btn-lg btn-primary\" href=\"#\">Learn more</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"carousel-caption text-end\">\r\n");
      out.write("            <h1>One more for good measure.</h1>\r\n");
      out.write("            <p>Some representative placeholder content for the third slide of this carousel.</p>\r\n");
      out.write("            <p><a class=\"btn btn-lg btn-primary\" href=\"#\">Browse gallery</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container marketing\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Three columns of text below the carousel -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <h2 class=\"fw-normal\">Heading</h2>\r\n");
      out.write("        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>\r\n");
      out.write("        <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("      </div><!-- /.col-lg-4 -->\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <h2 class=\"fw-normal\">Heading</h2>\r\n");
      out.write("        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>\r\n");
      out.write("        <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("      </div><!-- /.col-lg-4 -->\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <h2 class=\"fw-normal\">Heading</h2>\r\n");
      out.write("        <p>And lastly this, the third column of representative placeholder content.</p>\r\n");
      out.write("        <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("      </div><!-- /.col-lg-4 -->\r\n");
      out.write("    </div><!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <h2 class=\"fw-normal\">Heading</h2>\r\n");
      out.write("        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>\r\n");
      out.write("        <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("      </div><!-- /.col-lg-4 -->\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <h2 class=\"fw-normal\">Heading</h2>\r\n");
      out.write("        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>\r\n");
      out.write("        <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("      </div><!-- /.col-lg-4 -->\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><title>Placeholder</title><rect width=\"100%\" height=\"100%\" fill=\"var(--bs-secondary-color)\"/></svg>\r\n");
      out.write("        <h2 class=\"fw-normal\">Heading</h2>\r\n");
      out.write("        <p>And lastly this, the third column of representative placeholder content.</p>\r\n");
      out.write("        <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("      </div><!-- /.col-lg-4 -->\r\n");
      out.write("    </div><!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
