/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-29 06:21:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>모두의 레시피</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.css\">\r\n");
      out.write("    <script src=\"https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write("	@font-face {\r\n");
      out.write("		 font-family: 'NanumBarunGothic';\r\n");
      out.write("		 font-style: normal;\r\n");
      out.write("		 font-weight: 400;\r\n");
      out.write("		 src: url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWeb.eot');\r\n");
      out.write("		 src: url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWeb.eot?#iefix') format('embedded-opentype'), url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWeb.woff') format('woff'), url('//cdn.jsdelivr.net/font-nanumlight/1.0/NanumBarunGothicWeb.ttf') format('truetype');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.login-form {\r\n");
      out.write("	  	width: 500px;\r\n");
      out.write("	  	margin-right: auto;\r\n");
      out.write("	    margin-left: auto;\r\n");
      out.write("	    margin-top: 50px;\r\n");
      out.write("	    padding: 20px;\r\n");
      out.write("	  	text-align: center;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.i_d {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.id {\r\n");
      out.write("		float: center;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	  	border-bottom: 1px solid gray;\r\n");
      out.write("	    width: 200px;\r\n");
      out.write("	    margin-bottom: 10px;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.idcheck {\r\n");
      out.write("	   	  width: 65px;\r\n");
      out.write("	   	  height: 32px;\r\n");
      out.write("	   	  background-color: white;\r\n");
      out.write("	   	  border-radius: 25px;\r\n");
      out.write("	   	  border-color: gray;\r\n");
      out.write("	   	  cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.passwd {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.passwdche {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.pwd {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		float: center;\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	  	border-bottom: 1px solid gray;\r\n");
      out.write("	    width: 260px;\r\n");
      out.write("	    margin-bottom: 10px;\r\n");
      out.write("	    margin-left: -50px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.pwdCheck {\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("	  float: center;\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-bottom: 1px solid gray;\r\n");
      out.write("	  width: 260px;\r\n");
      out.write("	  margin-bottom: 10px;\r\n");
      out.write("	  margin-left: -80px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.Na {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.name {\r\n");
      out.write("		float: center;\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border: none;\r\n");
      out.write("	  border-bottom: 1px solid gray;\r\n");
      out.write("      width: 260px;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      margin-left: -30px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	.adr {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	.addresscheck {\r\n");
      out.write("		background-color: white;\r\n");
      out.write("	   	  border-radius: 25px;\r\n");
      out.write("	   	  border-color: gray;\r\n");
      out.write("	   	  cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#sample4_postcode {\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-bottom: 1px solid gray;\r\n");
      out.write("	  width: 220px;\r\n");
      out.write("	  margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#sample4_roadAddress {\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-bottom: 1px solid gray;\r\n");
      out.write("	  width: 260px;\r\n");
      out.write("	  margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#sample4_jibunAddress {\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-bottom: 1px solid gray;\r\n");
      out.write("	  width: 260px;\r\n");
      out.write("	  margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#sample4_detailAddress {\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-bottom: 1px solid gray;\r\n");
      out.write("	  width: 260px;\r\n");
      out.write("	  margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.join {\r\n");
      out.write("	  font-size: 14px;\r\n");
      out.write("	  border: 3px solid gray;\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  width: 260px;\r\n");
      out.write("	  background-color: white;\r\n");
      out.write("	  margin-bottom: 30px;\r\n");
      out.write("	  color: black;\r\n");
      out.write("	  cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.Administrator_Login {\r\n");
      out.write("	  background-color: white;\r\n");
      out.write("	  font-size: 15px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.title {\r\n");
      out.write("	  color: gray;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.dat {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.date {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	  	font-size: 14px;\r\n");
      out.write("	  	color: gray;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	p {\r\n");
      out.write("	  font-size: 13px;\r\n");
      out.write("	  color: gray;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.gen {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.col-tit {\r\n");
      out.write("		float: left;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		padding-top: 20px;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.col-content {\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("      	padding: 10px;\r\n");
      out.write("      	border: none;\r\n");
      out.write("      	width: 260px;\r\n");
      out.write("      	margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#HPhone1 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	  	border-bottom: 1px solid gray;\r\n");
      out.write("	    width: 50px;\r\n");
      out.write("	    margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#HPhone2 {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	  	border-bottom: 1px solid gray;\r\n");
      out.write("	    width: 50px;\r\n");
      out.write("	    margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.inpTxt {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	  	border-bottom: 1px solid gray;\r\n");
      out.write("	    width: 80px;\r\n");
      out.write("	    margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.select_email {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		width: 85px;\r\n");
      out.write("		height: 32px;\r\n");
      out.write("		line-height: 32px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.MS_select {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		width: 60px;\r\n");
      out.write("		height: 32px;\r\n");
      out.write("		line-height: 32px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.col_select {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		width: 50px;\r\n");
      out.write("		height: 32px;\r\n");
      out.write("		line-height: 32px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function sample4_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                var roadAddr = data.roadAddress;\r\n");
      out.write("                var extraRoadAddr = '';\r\n");
      out.write("\r\n");
      out.write("                if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                    extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                document.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("                document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("                document.getElementById(\"sample4_engAddress\").value = data.addressEnglish;\r\n");
      out.write("\r\n");
      out.write("                if (roadAddr !== '') {\r\n");
      out.write("                    document.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("\r\n");
      out.write("                if (data.autoRoadAddress) {\r\n");
      out.write("                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("                    guideTextBox.style.display = 'block';\r\n");
      out.write("                } else if (data.autoJibunAddress) {\r\n");
      out.write("                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("                    guideTextBox.style.display = 'block';\r\n");
      out.write("                } else {\r\n");
      out.write("                    guideTextBox.innerHTML = '';\r\n");
      out.write("                    guideTextBox.style.display = 'none';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("    function openZipSearch() {\r\n");
      out.write("  new  daum.Postcode( {\r\n");
      out.write("    oncomplete: function(data) {\r\n");
      out.write("      $('[name=zip]').val(data.zonecod);\r\n");
      out.write("      $('[name=addr1]').val(data.address);\r\n");
      out.write("      $('[name=addr2]').val(data.buildingName);\r\n");
      out.write("    }\r\n");
      out.write("  }).open();\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"login-form\">\r\n");
      out.write("    <h2 align=\"center\">Join</h2>\r\n");
      out.write("    <form action=\"/userJoin\" method=\"post\">\r\n");
      out.write("        <a class=\"i_d\">아이디</a>\r\n");
      out.write("        <input type=\"text\" class=\"id\" name=\"username\">\r\n");
      out.write("        <input type=\"submit\" class=\"idcheck\" name=\"username\" \" value=\"중복확인\">&nbsp;<br>\r\n");
      out.write("        <a class=\"passwd\">비밀번호</a>\r\n");
      out.write("        <input type=\"password\" class=\"pwd\" name=\"password\" ><br>\r\n");
      out.write("        <a class=\"passwdche\">비밀번호확인</a>\r\n");
      out.write("        <input type=\"password\" class=\"pwdCheck\" ><br>\r\n");
      out.write("        <a class=\"Na\">이름</a>\r\n");
      out.write("        <input type=\"text\" class=\"name\" name=\"name\" ><br>\r\n");
      out.write("        <a class=\"adr\">주소</a>\r\n");
      out.write("        <input type=\"text\" id=\"sample4_postcode\" name=\"address\" placeholder=\"우편번호\">\r\n");
      out.write("        <input type=\"button\" class=\"addresscheck\" onclick=\"sample4_execDaumPostcode()\" value=\"찾기\"><br>\r\n");
      out.write("        <input type=\"text\" id=\"sample4_roadAddress\" name=\"address\"  placeholder=\"도로명주소\" size=\"60\" ><br>\r\n");
      out.write("        <input type=\"hidden\" id=\"sample4_jibunAddress\" name=\"address\" placeholder=\"지번주소\"  size=\"60\">\r\n");
      out.write("        <span id=\"guide\" style=\"color:#999;display:none\"></span>\r\n");
      out.write("        <input type=\"text\" id=\"sample4_detailAddress\" name=\"address\"  placeholder=\"상세주소\"  size=\"60\"><br>\r\n");
      out.write("        <input type=\"hidden\" id=\"sample4_extraAddress\" placeholder=\"참고항목\"  size=\"60\">\r\n");
      out.write("        <input type=\"hidden\" id=\"sample4_engAddress\" placeholder=\"영문주소\"  size=\"60\" ><br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"birth\">\r\n");
      out.write("            <a class=\"dat\">생년월일</a>\r\n");
      out.write("            <input type=\"hidden\" class=\"date\" name=\"date\">\r\n");
      out.write("            <select name=\"date\"  class=\"MS_select MS_birthday\">\r\n");
      out.write("                <option value=\"\">생년</option>\r\n");
      out.write("                <option value=\"1920\">1920</option>\r\n");
      out.write("                <option value=\"1921\">1921</option>\r\n");
      out.write("                <option value=\"1922\">1922</option>\r\n");
      out.write("                <option value=\"1923\">1923</option>\r\n");
      out.write("                <option value=\"1924\">1924</option>\r\n");
      out.write("                <option value=\"1925\">1925</option>\r\n");
      out.write("                <option value=\"1926\">1926</option>\r\n");
      out.write("                <option value=\"1927\">1927</option>\r\n");
      out.write("                <option value=\"1928\">1928</option>\r\n");
      out.write("                <option value=\"1929\">1929</option>\r\n");
      out.write("                <option value=\"1930\">1930</option>\r\n");
      out.write("                <option value=\"1931\">1931</option>\r\n");
      out.write("                <option value=\"1932\">1932</option>\r\n");
      out.write("                <option value=\"1933\">1933</option>\r\n");
      out.write("                <option value=\"1934\">1934</option>\r\n");
      out.write("                <option value=\"1935\">1935</option>\r\n");
      out.write("                <option value=\"1936\">1936</option>\r\n");
      out.write("                <option value=\"1937\">1937</option>\r\n");
      out.write("                <option value=\"1938\">1938</option>\r\n");
      out.write("                <option value=\"1939\">1939</option>\r\n");
      out.write("                <option value=\"1940\">1940</option>\r\n");
      out.write("                <option value=\"1941\">1941</option>\r\n");
      out.write("                <option value=\"1942\">1942</option>\r\n");
      out.write("                <option value=\"1943\">1943</option>\r\n");
      out.write("                <option value=\"1944\">1944</option>\r\n");
      out.write("                <option value=\"1945\">1945</option>\r\n");
      out.write("                <option value=\"1946\">1946</option>\r\n");
      out.write("                <option value=\"1947\">1947</option>\r\n");
      out.write("                <option value=\"1948\">1948</option>\r\n");
      out.write("                <option value=\"1949\">1949</option>\r\n");
      out.write("                <option value=\"1950\">1950</option>\r\n");
      out.write("                <option value=\"1951\">1951</option>\r\n");
      out.write("                <option value=\"1952\">1952</option>\r\n");
      out.write("                <option value=\"1953\">1953</option>\r\n");
      out.write("                <option value=\"1954\">1954</option>\r\n");
      out.write("                <option value=\"1955\">1955</option>\r\n");
      out.write("                <option value=\"1956\">1956</option>\r\n");
      out.write("                <option value=\"1957\">1957</option>\r\n");
      out.write("                <option value=\"1958\">1958</option>\r\n");
      out.write("                <option value=\"1959\">1959</option>\r\n");
      out.write("                <option value=\"1960\">1960</option>\r\n");
      out.write("                <option value=\"1961\">1961</option>\r\n");
      out.write("                <option value=\"1962\">1962</option>\r\n");
      out.write("                <option value=\"1963\">1963</option>\r\n");
      out.write("                <option value=\"1964\">1964</option>\r\n");
      out.write("                <option value=\"1965\">1965</option>\r\n");
      out.write("                <option value=\"1966\">1966</option>\r\n");
      out.write("                <option value=\"1967\">1967</option>\r\n");
      out.write("                <option value=\"1968\">1968</option>\r\n");
      out.write("                <option value=\"1969\">1969</option>\r\n");
      out.write("                <option value=\"1970\">1970</option>\r\n");
      out.write("                <option value=\"1971\">1971</option>\r\n");
      out.write("                <option value=\"1972\">1972</option>\r\n");
      out.write("                <option value=\"1973\">1973</option>\r\n");
      out.write("                <option value=\"1974\">1974</option>\r\n");
      out.write("                <option value=\"1975\">1975</option>\r\n");
      out.write("                <option value=\"1976\">1976</option>\r\n");
      out.write("                <option value=\"1977\">1977</option>\r\n");
      out.write("                <option value=\"1978\">1978</option>\r\n");
      out.write("                <option value=\"1979\">1979</option>\r\n");
      out.write("                <option value=\"1980\">1980</option>\r\n");
      out.write("                <option value=\"1981\">1981</option>\r\n");
      out.write("                <option value=\"1982\">1982</option>\r\n");
      out.write("                <option value=\"1983\">1983</option>\r\n");
      out.write("                <option value=\"1984\">1984</option>\r\n");
      out.write("                <option value=\"1985\">1985</option>\r\n");
      out.write("                <option value=\"1986\">1986</option>\r\n");
      out.write("                <option value=\"1987\">1987</option>\r\n");
      out.write("                <option value=\"1988\">1988</option>\r\n");
      out.write("                <option value=\"1989\">1989</option>\r\n");
      out.write("                <option value=\"1990\">1990</option>\r\n");
      out.write("                <option value=\"1991\">1991</option>\r\n");
      out.write("                <option value=\"1992\">1992</option>\r\n");
      out.write("                <option value=\"1993\">1993</option>\r\n");
      out.write("                <option value=\"1994\">1994</option>\r\n");
      out.write("                <option value=\"1995\">1995</option>\r\n");
      out.write("                <option value=\"1996\">1996</option>\r\n");
      out.write("                <option value=\"1997\">1997</option>\r\n");
      out.write("                <option value=\"1998\">1998</option>\r\n");
      out.write("                <option value=\"1999\">1999</option>\r\n");
      out.write("                <option value=\"2000\">2000</option>\r\n");
      out.write("                <option value=\"2001\">2001</option>\r\n");
      out.write("                <option value=\"2002\">2002</option>\r\n");
      out.write("                <option value=\"2003\">2003</option>\r\n");
      out.write("                <option value=\"2004\">2004</option>\r\n");
      out.write("                <option value=\"2005\">2005</option>\r\n");
      out.write("                <option value=\"2006\">2006</option>\r\n");
      out.write("                <option value=\"2007\">2007</option>\r\n");
      out.write("                <option value=\"2008\">2008</option>\r\n");
      out.write("                <option value=\"2009\">2009</option>\r\n");
      out.write("                <option value=\"2010\">2010</option>\r\n");
      out.write("                <option value=\"2011\">2011</option>\r\n");
      out.write("                <option value=\"2012\">2012</option>\r\n");
      out.write("                <option value=\"2013\">2013</option>\r\n");
      out.write("                <option value=\"2014\">2014</option>\r\n");
      out.write("                <option value=\"2015\">2015</option>\r\n");
      out.write("                <option value=\"2016\">2016</option>\r\n");
      out.write("                <option value=\"2017\">2017</option>\r\n");
      out.write("                <option value=\"2018\">2018</option>\r\n");
      out.write("                <option value=\"2019\">2019</option>\r\n");
      out.write("                <option value=\"2020\">2020</option>\r\n");
      out.write("                <option value=\"2021\">2021</option>\r\n");
      out.write("                <option value=\"2021\">2022/option>\r\n");
      out.write("                <option value=\"2021\">2023</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            년\r\n");
      out.write("            <select name=\"date\" class=\"MS_select MS_birthday\">\r\n");
      out.write("                <option value=\"\">월</option>\r\n");
      out.write("                <option value=\"01\">1</option>\r\n");
      out.write("                <option value=\"02\">2</option>\r\n");
      out.write("                <option value=\"03\">3</option>\r\n");
      out.write("                <option value=\"04\">4</option>\r\n");
      out.write("                <option value=\"05\">5</option>\r\n");
      out.write("                <option value=\"06\">6</option>\r\n");
      out.write("                <option value=\"07\">7</option>\r\n");
      out.write("                <option value=\"08\">8</option>\r\n");
      out.write("                <option value=\"09\">9</option>\r\n");
      out.write("                <option value=\"10\">10</option>\r\n");
      out.write("                <option value=\"11\">11</option>\r\n");
      out.write("                <option value=\"12\">12</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            월\r\n");
      out.write("            <select name=\"date\"  class=\"MS_select MS_birthday\">\r\n");
      out.write("                <option value=\"\">일</option>\r\n");
      out.write("                <option value=\"01\">1</option>\r\n");
      out.write("                <option value=\"02\">2</option>\r\n");
      out.write("                <option value=\"03\">3</option>\r\n");
      out.write("                <option value=\"04\">4</option>\r\n");
      out.write("                <option value=\"05\">5</option>\r\n");
      out.write("                <option value=\"06\">6</option>\r\n");
      out.write("                <option value=\"07\">7</option>\r\n");
      out.write("                <option value=\"08\">8</option>\r\n");
      out.write("                <option value=\"09\">9</option>\r\n");
      out.write("                <option value=\"10\">10</option>\r\n");
      out.write("                <option value=\"11\">11</option>\r\n");
      out.write("                <option value=\"12\">12</option>\r\n");
      out.write("                <option value=\"13\">13</option>\r\n");
      out.write("                <option value=\"14\">14</option>\r\n");
      out.write("                <option value=\"15\">15</option>\r\n");
      out.write("                <option value=\"16\">16</option>\r\n");
      out.write("                <option value=\"17\">17</option>\r\n");
      out.write("                <option value=\"18\">18</option>\r\n");
      out.write("                <option value=\"19\">19</option>\r\n");
      out.write("                <option value=\"20\">20</option>\r\n");
      out.write("                <option value=\"21\">21</option>\r\n");
      out.write("                <option value=\"22\">22</option>\r\n");
      out.write("                <option value=\"23\">23</option>\r\n");
      out.write("                <option value=\"24\">24</option>\r\n");
      out.write("                <option value=\"25\">25</option>\r\n");
      out.write("                <option value=\"26\">26</option>\r\n");
      out.write("                <option value=\"27\">27</option>\r\n");
      out.write("                <option value=\"28\">28</option>\r\n");
      out.write("                <option value=\"29\">29</option>\r\n");
      out.write("                <option value=\"30\">30</option>\r\n");
      out.write("                <option value=\"31\">31</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            일\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <span class=\"interest\">관심목록</span>\r\n");
      out.write("        <select name=\"interest\" id=\"interest\">\r\n");
      out.write("        	<option>1</option>\r\n");
      out.write("        	<option>2</option>\r\n");
      out.write("        	<option>3</option>\r\n");
      out.write("        	<option>4</option>\r\n");
      out.write("        	<option>5</option>\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"col-tit\">휴대폰</div>\r\n");
      out.write("        <div class=\"col-content\">\r\n");
      out.write("            <select class=\"col_select\" name=\"phone\"  >\r\n");
      out.write("                <option value=\"010\">010</option>\r\n");
      out.write("                <option value=\"011\">011</option>\r\n");
      out.write("                <option value=\"016\">016</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            -\r\n");
      out.write("            <input type=\"text\" id=\"HPhone1\" class=\"inpTxt\" name=\"phone\" >\r\n");
      out.write("            -\r\n");
      out.write("            <input type=\"text\" id=\"HPhone2\" class=\"inpTxt\" name=\"phone\" >\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <input type=\"submit\" class=\"join\" value=\"가입하기\">\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
