member/listBoard.do=com.sist.action.ListBoardAction
member/insertBoard.do=com.sist.action.InsertBoardAction
member/insertBoardOK.do=com.sist.action.InsertBoardOKAction
member/boardDetail.do=com.sist.action.BoardDetailAction
member/updateBoard.do=com.sist.action.UpdateBoardAction
member/updateBoardOK.do=com.sist.action.UpdateBoardOKAction
member/deleteBoard.do=com.sist.action.DeleteBoardAction
member/deleteBoardOK.do=com.sist.action.DeleteBoardOKAction
joinMember.do=com.sist.action.JoinMemberAction
joinMemberOK.do=com.sist.action.JoinMemberOKAction
login.do=com.sist.action.LoginAction
loginOK.do=com.sist.action.LoginOKAction