member/listBoard.do=action.ListBoardAction
member/insertBoard.do=action.InsertBoardAction
member/insertBoardOK.do=action.InsertBoardOKAction
member/boardDetail.do=action.DetailBoardAction

login.do=action.LoginAction
loginOK.do=action.LoginOKAction
